name: regression-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.0
  - numpy>=1.24
  - matplotlib>=3.7
  - scipy>=1.10
  - scikit-learn>=1.3
  - jupyter
  - notebook
  - ipykernel
  - nbconvert
  - r-base>=4.3
  - r-irkernel
  - r-ggplot2
  - r-jsonlite
